/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadoRouteImport } from './routes/resultado'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as CriarRouteImport } from './routes/criar'
import { Route as IndexRouteImport } from './routes/index'

const ResultadoRoute = ResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarRoute = CriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/premium': typeof PremiumRoute
  '/resultado': typeof ResultadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/premium': typeof PremiumRoute
  '/resultado': typeof ResultadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar': typeof CriarRoute
  '/premium': typeof PremiumRoute
  '/resultado': typeof ResultadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/criar' | '/premium' | '/resultado'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/criar' | '/premium' | '/resultado'
  id: '__root__' | '/' | '/criar' | '/premium' | '/resultado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarRoute: typeof CriarRoute
  PremiumRoute: typeof PremiumRoute
  ResultadoRoute: typeof ResultadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultado': {
      id: '/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof ResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar': {
      id: '/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof CriarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarRoute: CriarRoute,
  PremiumRoute: PremiumRoute,
  ResultadoRoute: ResultadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
